/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.cj.prototype.avroGenerated;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class LoyaltyPoints extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5922345794222522913L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LoyaltyPoints\",\"namespace\":\"com.cj.prototype.avroGenerated\",\"fields\":[{\"name\":\"name\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"points\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"ratio\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<LoyaltyPoints> ENCODER =
      new BinaryMessageEncoder<LoyaltyPoints>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<LoyaltyPoints> DECODER =
      new BinaryMessageDecoder<LoyaltyPoints>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<LoyaltyPoints> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<LoyaltyPoints> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<LoyaltyPoints> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<LoyaltyPoints>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this LoyaltyPoints to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a LoyaltyPoints from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a LoyaltyPoints instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static LoyaltyPoints fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence name;
   private java.lang.Integer points;
   private java.lang.CharSequence ratio;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LoyaltyPoints() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param points The new value for points
   * @param ratio The new value for ratio
   */
  public LoyaltyPoints(java.lang.CharSequence name, java.lang.Integer points, java.lang.CharSequence ratio) {
    this.name = name;
    this.points = points;
    this.ratio = ratio;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return points;
    case 2: return ratio;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: points = (java.lang.Integer)value$; break;
    case 2: ratio = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'points' field.
   * @return The value of the 'points' field.
   */
  public java.lang.Integer getPoints() {
    return points;
  }


  /**
   * Sets the value of the 'points' field.
   * @param value the value to set.
   */
  public void setPoints(java.lang.Integer value) {
    this.points = value;
  }

  /**
   * Gets the value of the 'ratio' field.
   * @return The value of the 'ratio' field.
   */
  public java.lang.CharSequence getRatio() {
    return ratio;
  }


  /**
   * Sets the value of the 'ratio' field.
   * @param value the value to set.
   */
  public void setRatio(java.lang.CharSequence value) {
    this.ratio = value;
  }

  /**
   * Creates a new LoyaltyPoints RecordBuilder.
   * @return A new LoyaltyPoints RecordBuilder
   */
  public static com.cj.prototype.avroGenerated.LoyaltyPoints.Builder newBuilder() {
    return new com.cj.prototype.avroGenerated.LoyaltyPoints.Builder();
  }

  /**
   * Creates a new LoyaltyPoints RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LoyaltyPoints RecordBuilder
   */
  public static com.cj.prototype.avroGenerated.LoyaltyPoints.Builder newBuilder(com.cj.prototype.avroGenerated.LoyaltyPoints.Builder other) {
    if (other == null) {
      return new com.cj.prototype.avroGenerated.LoyaltyPoints.Builder();
    } else {
      return new com.cj.prototype.avroGenerated.LoyaltyPoints.Builder(other);
    }
  }

  /**
   * Creates a new LoyaltyPoints RecordBuilder by copying an existing LoyaltyPoints instance.
   * @param other The existing instance to copy.
   * @return A new LoyaltyPoints RecordBuilder
   */
  public static com.cj.prototype.avroGenerated.LoyaltyPoints.Builder newBuilder(com.cj.prototype.avroGenerated.LoyaltyPoints other) {
    if (other == null) {
      return new com.cj.prototype.avroGenerated.LoyaltyPoints.Builder();
    } else {
      return new com.cj.prototype.avroGenerated.LoyaltyPoints.Builder(other);
    }
  }

  /**
   * RecordBuilder for LoyaltyPoints instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LoyaltyPoints>
    implements org.apache.avro.data.RecordBuilder<LoyaltyPoints> {

    private java.lang.CharSequence name;
    private java.lang.Integer points;
    private java.lang.CharSequence ratio;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.cj.prototype.avroGenerated.LoyaltyPoints.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.points)) {
        this.points = data().deepCopy(fields()[1].schema(), other.points);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.ratio)) {
        this.ratio = data().deepCopy(fields()[2].schema(), other.ratio);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing LoyaltyPoints instance
     * @param other The existing instance to copy.
     */
    private Builder(com.cj.prototype.avroGenerated.LoyaltyPoints other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.points)) {
        this.points = data().deepCopy(fields()[1].schema(), other.points);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ratio)) {
        this.ratio = data().deepCopy(fields()[2].schema(), other.ratio);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.cj.prototype.avroGenerated.LoyaltyPoints.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.cj.prototype.avroGenerated.LoyaltyPoints.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'points' field.
      * @return The value.
      */
    public java.lang.Integer getPoints() {
      return points;
    }


    /**
      * Sets the value of the 'points' field.
      * @param value The value of 'points'.
      * @return This builder.
      */
    public com.cj.prototype.avroGenerated.LoyaltyPoints.Builder setPoints(java.lang.Integer value) {
      validate(fields()[1], value);
      this.points = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'points' field has been set.
      * @return True if the 'points' field has been set, false otherwise.
      */
    public boolean hasPoints() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'points' field.
      * @return This builder.
      */
    public com.cj.prototype.avroGenerated.LoyaltyPoints.Builder clearPoints() {
      points = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'ratio' field.
      * @return The value.
      */
    public java.lang.CharSequence getRatio() {
      return ratio;
    }


    /**
      * Sets the value of the 'ratio' field.
      * @param value The value of 'ratio'.
      * @return This builder.
      */
    public com.cj.prototype.avroGenerated.LoyaltyPoints.Builder setRatio(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.ratio = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'ratio' field has been set.
      * @return True if the 'ratio' field has been set, false otherwise.
      */
    public boolean hasRatio() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'ratio' field.
      * @return This builder.
      */
    public com.cj.prototype.avroGenerated.LoyaltyPoints.Builder clearRatio() {
      ratio = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public LoyaltyPoints build() {
      try {
        LoyaltyPoints record = new LoyaltyPoints();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.points = fieldSetFlags()[1] ? this.points : (java.lang.Integer) defaultValue(fields()[1]);
        record.ratio = fieldSetFlags()[2] ? this.ratio : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<LoyaltyPoints>
    WRITER$ = (org.apache.avro.io.DatumWriter<LoyaltyPoints>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<LoyaltyPoints>
    READER$ = (org.apache.avro.io.DatumReader<LoyaltyPoints>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.name == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.name);
    }

    if (this.points == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.points);
    }

    if (this.ratio == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.ratio);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.name = null;
      } else {
        this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.points = null;
      } else {
        this.points = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.ratio = null;
      } else {
        this.ratio = in.readString(this.ratio instanceof Utf8 ? (Utf8)this.ratio : null);
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.name = null;
          } else {
            this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.points = null;
          } else {
            this.points = in.readInt();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.ratio = null;
          } else {
            this.ratio = in.readString(this.ratio instanceof Utf8 ? (Utf8)this.ratio : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










