/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.cj.prototype.avroGenerated;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Shipping extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1307327066712932506L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Shipping\",\"namespace\":\"com.cj.prototype.avroGenerated\",\"fields\":[{\"name\":\"price\",\"type\":{\"type\":\"record\",\"name\":\"AmountWithCurrency\",\"fields\":[{\"name\":\"amount\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"currency\",\"type\":[\"null\",\"string\"],\"default\":null}]}},{\"name\":\"service\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"locationGroupName\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"region\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"postalCode\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"locationId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"country\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"weight\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"length\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"width\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"height\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Shipping> ENCODER =
      new BinaryMessageEncoder<Shipping>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Shipping> DECODER =
      new BinaryMessageDecoder<Shipping>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Shipping> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Shipping> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Shipping> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Shipping>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Shipping to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Shipping from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Shipping instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Shipping fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private com.cj.prototype.avroGenerated.AmountWithCurrency price;
   private java.lang.CharSequence service;
   private java.lang.CharSequence locationGroupName;
   private java.lang.CharSequence region;
   private java.lang.CharSequence postalCode;
   private java.lang.CharSequence locationId;
   private java.lang.CharSequence country;
   private java.lang.CharSequence weight;
   private java.lang.CharSequence length;
   private java.lang.CharSequence width;
   private java.lang.CharSequence height;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Shipping() {}

  /**
   * All-args constructor.
   * @param price The new value for price
   * @param service The new value for service
   * @param locationGroupName The new value for locationGroupName
   * @param region The new value for region
   * @param postalCode The new value for postalCode
   * @param locationId The new value for locationId
   * @param country The new value for country
   * @param weight The new value for weight
   * @param length The new value for length
   * @param width The new value for width
   * @param height The new value for height
   */
  public Shipping(com.cj.prototype.avroGenerated.AmountWithCurrency price, java.lang.CharSequence service, java.lang.CharSequence locationGroupName, java.lang.CharSequence region, java.lang.CharSequence postalCode, java.lang.CharSequence locationId, java.lang.CharSequence country, java.lang.CharSequence weight, java.lang.CharSequence length, java.lang.CharSequence width, java.lang.CharSequence height) {
    this.price = price;
    this.service = service;
    this.locationGroupName = locationGroupName;
    this.region = region;
    this.postalCode = postalCode;
    this.locationId = locationId;
    this.country = country;
    this.weight = weight;
    this.length = length;
    this.width = width;
    this.height = height;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return price;
    case 1: return service;
    case 2: return locationGroupName;
    case 3: return region;
    case 4: return postalCode;
    case 5: return locationId;
    case 6: return country;
    case 7: return weight;
    case 8: return length;
    case 9: return width;
    case 10: return height;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: price = (com.cj.prototype.avroGenerated.AmountWithCurrency)value$; break;
    case 1: service = (java.lang.CharSequence)value$; break;
    case 2: locationGroupName = (java.lang.CharSequence)value$; break;
    case 3: region = (java.lang.CharSequence)value$; break;
    case 4: postalCode = (java.lang.CharSequence)value$; break;
    case 5: locationId = (java.lang.CharSequence)value$; break;
    case 6: country = (java.lang.CharSequence)value$; break;
    case 7: weight = (java.lang.CharSequence)value$; break;
    case 8: length = (java.lang.CharSequence)value$; break;
    case 9: width = (java.lang.CharSequence)value$; break;
    case 10: height = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'price' field.
   * @return The value of the 'price' field.
   */
  public com.cj.prototype.avroGenerated.AmountWithCurrency getPrice() {
    return price;
  }


  /**
   * Sets the value of the 'price' field.
   * @param value the value to set.
   */
  public void setPrice(com.cj.prototype.avroGenerated.AmountWithCurrency value) {
    this.price = value;
  }

  /**
   * Gets the value of the 'service' field.
   * @return The value of the 'service' field.
   */
  public java.lang.CharSequence getService() {
    return service;
  }


  /**
   * Sets the value of the 'service' field.
   * @param value the value to set.
   */
  public void setService(java.lang.CharSequence value) {
    this.service = value;
  }

  /**
   * Gets the value of the 'locationGroupName' field.
   * @return The value of the 'locationGroupName' field.
   */
  public java.lang.CharSequence getLocationGroupName() {
    return locationGroupName;
  }


  /**
   * Sets the value of the 'locationGroupName' field.
   * @param value the value to set.
   */
  public void setLocationGroupName(java.lang.CharSequence value) {
    this.locationGroupName = value;
  }

  /**
   * Gets the value of the 'region' field.
   * @return The value of the 'region' field.
   */
  public java.lang.CharSequence getRegion() {
    return region;
  }


  /**
   * Sets the value of the 'region' field.
   * @param value the value to set.
   */
  public void setRegion(java.lang.CharSequence value) {
    this.region = value;
  }

  /**
   * Gets the value of the 'postalCode' field.
   * @return The value of the 'postalCode' field.
   */
  public java.lang.CharSequence getPostalCode() {
    return postalCode;
  }


  /**
   * Sets the value of the 'postalCode' field.
   * @param value the value to set.
   */
  public void setPostalCode(java.lang.CharSequence value) {
    this.postalCode = value;
  }

  /**
   * Gets the value of the 'locationId' field.
   * @return The value of the 'locationId' field.
   */
  public java.lang.CharSequence getLocationId() {
    return locationId;
  }


  /**
   * Sets the value of the 'locationId' field.
   * @param value the value to set.
   */
  public void setLocationId(java.lang.CharSequence value) {
    this.locationId = value;
  }

  /**
   * Gets the value of the 'country' field.
   * @return The value of the 'country' field.
   */
  public java.lang.CharSequence getCountry() {
    return country;
  }


  /**
   * Sets the value of the 'country' field.
   * @param value the value to set.
   */
  public void setCountry(java.lang.CharSequence value) {
    this.country = value;
  }

  /**
   * Gets the value of the 'weight' field.
   * @return The value of the 'weight' field.
   */
  public java.lang.CharSequence getWeight() {
    return weight;
  }


  /**
   * Sets the value of the 'weight' field.
   * @param value the value to set.
   */
  public void setWeight(java.lang.CharSequence value) {
    this.weight = value;
  }

  /**
   * Gets the value of the 'length' field.
   * @return The value of the 'length' field.
   */
  public java.lang.CharSequence getLength() {
    return length;
  }


  /**
   * Sets the value of the 'length' field.
   * @param value the value to set.
   */
  public void setLength(java.lang.CharSequence value) {
    this.length = value;
  }

  /**
   * Gets the value of the 'width' field.
   * @return The value of the 'width' field.
   */
  public java.lang.CharSequence getWidth() {
    return width;
  }


  /**
   * Sets the value of the 'width' field.
   * @param value the value to set.
   */
  public void setWidth(java.lang.CharSequence value) {
    this.width = value;
  }

  /**
   * Gets the value of the 'height' field.
   * @return The value of the 'height' field.
   */
  public java.lang.CharSequence getHeight() {
    return height;
  }


  /**
   * Sets the value of the 'height' field.
   * @param value the value to set.
   */
  public void setHeight(java.lang.CharSequence value) {
    this.height = value;
  }

  /**
   * Creates a new Shipping RecordBuilder.
   * @return A new Shipping RecordBuilder
   */
  public static com.cj.prototype.avroGenerated.Shipping.Builder newBuilder() {
    return new com.cj.prototype.avroGenerated.Shipping.Builder();
  }

  /**
   * Creates a new Shipping RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Shipping RecordBuilder
   */
  public static com.cj.prototype.avroGenerated.Shipping.Builder newBuilder(com.cj.prototype.avroGenerated.Shipping.Builder other) {
    if (other == null) {
      return new com.cj.prototype.avroGenerated.Shipping.Builder();
    } else {
      return new com.cj.prototype.avroGenerated.Shipping.Builder(other);
    }
  }

  /**
   * Creates a new Shipping RecordBuilder by copying an existing Shipping instance.
   * @param other The existing instance to copy.
   * @return A new Shipping RecordBuilder
   */
  public static com.cj.prototype.avroGenerated.Shipping.Builder newBuilder(com.cj.prototype.avroGenerated.Shipping other) {
    if (other == null) {
      return new com.cj.prototype.avroGenerated.Shipping.Builder();
    } else {
      return new com.cj.prototype.avroGenerated.Shipping.Builder(other);
    }
  }

  /**
   * RecordBuilder for Shipping instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Shipping>
    implements org.apache.avro.data.RecordBuilder<Shipping> {

    private com.cj.prototype.avroGenerated.AmountWithCurrency price;
    private com.cj.prototype.avroGenerated.AmountWithCurrency.Builder priceBuilder;
    private java.lang.CharSequence service;
    private java.lang.CharSequence locationGroupName;
    private java.lang.CharSequence region;
    private java.lang.CharSequence postalCode;
    private java.lang.CharSequence locationId;
    private java.lang.CharSequence country;
    private java.lang.CharSequence weight;
    private java.lang.CharSequence length;
    private java.lang.CharSequence width;
    private java.lang.CharSequence height;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.cj.prototype.avroGenerated.Shipping.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.price)) {
        this.price = data().deepCopy(fields()[0].schema(), other.price);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasPriceBuilder()) {
        this.priceBuilder = com.cj.prototype.avroGenerated.AmountWithCurrency.newBuilder(other.getPriceBuilder());
      }
      if (isValidValue(fields()[1], other.service)) {
        this.service = data().deepCopy(fields()[1].schema(), other.service);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.locationGroupName)) {
        this.locationGroupName = data().deepCopy(fields()[2].schema(), other.locationGroupName);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.region)) {
        this.region = data().deepCopy(fields()[3].schema(), other.region);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.postalCode)) {
        this.postalCode = data().deepCopy(fields()[4].schema(), other.postalCode);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.locationId)) {
        this.locationId = data().deepCopy(fields()[5].schema(), other.locationId);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.country)) {
        this.country = data().deepCopy(fields()[6].schema(), other.country);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.weight)) {
        this.weight = data().deepCopy(fields()[7].schema(), other.weight);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.length)) {
        this.length = data().deepCopy(fields()[8].schema(), other.length);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.width)) {
        this.width = data().deepCopy(fields()[9].schema(), other.width);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.height)) {
        this.height = data().deepCopy(fields()[10].schema(), other.height);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
    }

    /**
     * Creates a Builder by copying an existing Shipping instance
     * @param other The existing instance to copy.
     */
    private Builder(com.cj.prototype.avroGenerated.Shipping other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.price)) {
        this.price = data().deepCopy(fields()[0].schema(), other.price);
        fieldSetFlags()[0] = true;
      }
      this.priceBuilder = null;
      if (isValidValue(fields()[1], other.service)) {
        this.service = data().deepCopy(fields()[1].schema(), other.service);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.locationGroupName)) {
        this.locationGroupName = data().deepCopy(fields()[2].schema(), other.locationGroupName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.region)) {
        this.region = data().deepCopy(fields()[3].schema(), other.region);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.postalCode)) {
        this.postalCode = data().deepCopy(fields()[4].schema(), other.postalCode);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.locationId)) {
        this.locationId = data().deepCopy(fields()[5].schema(), other.locationId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.country)) {
        this.country = data().deepCopy(fields()[6].schema(), other.country);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.weight)) {
        this.weight = data().deepCopy(fields()[7].schema(), other.weight);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.length)) {
        this.length = data().deepCopy(fields()[8].schema(), other.length);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.width)) {
        this.width = data().deepCopy(fields()[9].schema(), other.width);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.height)) {
        this.height = data().deepCopy(fields()[10].schema(), other.height);
        fieldSetFlags()[10] = true;
      }
    }

    /**
      * Gets the value of the 'price' field.
      * @return The value.
      */
    public com.cj.prototype.avroGenerated.AmountWithCurrency getPrice() {
      return price;
    }


    /**
      * Sets the value of the 'price' field.
      * @param value The value of 'price'.
      * @return This builder.
      */
    public com.cj.prototype.avroGenerated.Shipping.Builder setPrice(com.cj.prototype.avroGenerated.AmountWithCurrency value) {
      validate(fields()[0], value);
      this.priceBuilder = null;
      this.price = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'price' field has been set.
      * @return True if the 'price' field has been set, false otherwise.
      */
    public boolean hasPrice() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'price' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.cj.prototype.avroGenerated.AmountWithCurrency.Builder getPriceBuilder() {
      if (priceBuilder == null) {
        if (hasPrice()) {
          setPriceBuilder(com.cj.prototype.avroGenerated.AmountWithCurrency.newBuilder(price));
        } else {
          setPriceBuilder(com.cj.prototype.avroGenerated.AmountWithCurrency.newBuilder());
        }
      }
      return priceBuilder;
    }

    /**
     * Sets the Builder instance for the 'price' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.cj.prototype.avroGenerated.Shipping.Builder setPriceBuilder(com.cj.prototype.avroGenerated.AmountWithCurrency.Builder value) {
      clearPrice();
      priceBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'price' field has an active Builder instance
     * @return True if the 'price' field has an active Builder instance
     */
    public boolean hasPriceBuilder() {
      return priceBuilder != null;
    }

    /**
      * Clears the value of the 'price' field.
      * @return This builder.
      */
    public com.cj.prototype.avroGenerated.Shipping.Builder clearPrice() {
      price = null;
      priceBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'service' field.
      * @return The value.
      */
    public java.lang.CharSequence getService() {
      return service;
    }


    /**
      * Sets the value of the 'service' field.
      * @param value The value of 'service'.
      * @return This builder.
      */
    public com.cj.prototype.avroGenerated.Shipping.Builder setService(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.service = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'service' field has been set.
      * @return True if the 'service' field has been set, false otherwise.
      */
    public boolean hasService() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'service' field.
      * @return This builder.
      */
    public com.cj.prototype.avroGenerated.Shipping.Builder clearService() {
      service = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'locationGroupName' field.
      * @return The value.
      */
    public java.lang.CharSequence getLocationGroupName() {
      return locationGroupName;
    }


    /**
      * Sets the value of the 'locationGroupName' field.
      * @param value The value of 'locationGroupName'.
      * @return This builder.
      */
    public com.cj.prototype.avroGenerated.Shipping.Builder setLocationGroupName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.locationGroupName = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'locationGroupName' field has been set.
      * @return True if the 'locationGroupName' field has been set, false otherwise.
      */
    public boolean hasLocationGroupName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'locationGroupName' field.
      * @return This builder.
      */
    public com.cj.prototype.avroGenerated.Shipping.Builder clearLocationGroupName() {
      locationGroupName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'region' field.
      * @return The value.
      */
    public java.lang.CharSequence getRegion() {
      return region;
    }


    /**
      * Sets the value of the 'region' field.
      * @param value The value of 'region'.
      * @return This builder.
      */
    public com.cj.prototype.avroGenerated.Shipping.Builder setRegion(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.region = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'region' field has been set.
      * @return True if the 'region' field has been set, false otherwise.
      */
    public boolean hasRegion() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'region' field.
      * @return This builder.
      */
    public com.cj.prototype.avroGenerated.Shipping.Builder clearRegion() {
      region = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'postalCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getPostalCode() {
      return postalCode;
    }


    /**
      * Sets the value of the 'postalCode' field.
      * @param value The value of 'postalCode'.
      * @return This builder.
      */
    public com.cj.prototype.avroGenerated.Shipping.Builder setPostalCode(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.postalCode = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'postalCode' field has been set.
      * @return True if the 'postalCode' field has been set, false otherwise.
      */
    public boolean hasPostalCode() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'postalCode' field.
      * @return This builder.
      */
    public com.cj.prototype.avroGenerated.Shipping.Builder clearPostalCode() {
      postalCode = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'locationId' field.
      * @return The value.
      */
    public java.lang.CharSequence getLocationId() {
      return locationId;
    }


    /**
      * Sets the value of the 'locationId' field.
      * @param value The value of 'locationId'.
      * @return This builder.
      */
    public com.cj.prototype.avroGenerated.Shipping.Builder setLocationId(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.locationId = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'locationId' field has been set.
      * @return True if the 'locationId' field has been set, false otherwise.
      */
    public boolean hasLocationId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'locationId' field.
      * @return This builder.
      */
    public com.cj.prototype.avroGenerated.Shipping.Builder clearLocationId() {
      locationId = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'country' field.
      * @return The value.
      */
    public java.lang.CharSequence getCountry() {
      return country;
    }


    /**
      * Sets the value of the 'country' field.
      * @param value The value of 'country'.
      * @return This builder.
      */
    public com.cj.prototype.avroGenerated.Shipping.Builder setCountry(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.country = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'country' field has been set.
      * @return True if the 'country' field has been set, false otherwise.
      */
    public boolean hasCountry() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'country' field.
      * @return This builder.
      */
    public com.cj.prototype.avroGenerated.Shipping.Builder clearCountry() {
      country = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'weight' field.
      * @return The value.
      */
    public java.lang.CharSequence getWeight() {
      return weight;
    }


    /**
      * Sets the value of the 'weight' field.
      * @param value The value of 'weight'.
      * @return This builder.
      */
    public com.cj.prototype.avroGenerated.Shipping.Builder setWeight(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.weight = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'weight' field has been set.
      * @return True if the 'weight' field has been set, false otherwise.
      */
    public boolean hasWeight() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'weight' field.
      * @return This builder.
      */
    public com.cj.prototype.avroGenerated.Shipping.Builder clearWeight() {
      weight = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'length' field.
      * @return The value.
      */
    public java.lang.CharSequence getLength() {
      return length;
    }


    /**
      * Sets the value of the 'length' field.
      * @param value The value of 'length'.
      * @return This builder.
      */
    public com.cj.prototype.avroGenerated.Shipping.Builder setLength(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.length = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'length' field has been set.
      * @return True if the 'length' field has been set, false otherwise.
      */
    public boolean hasLength() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'length' field.
      * @return This builder.
      */
    public com.cj.prototype.avroGenerated.Shipping.Builder clearLength() {
      length = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'width' field.
      * @return The value.
      */
    public java.lang.CharSequence getWidth() {
      return width;
    }


    /**
      * Sets the value of the 'width' field.
      * @param value The value of 'width'.
      * @return This builder.
      */
    public com.cj.prototype.avroGenerated.Shipping.Builder setWidth(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.width = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'width' field has been set.
      * @return True if the 'width' field has been set, false otherwise.
      */
    public boolean hasWidth() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'width' field.
      * @return This builder.
      */
    public com.cj.prototype.avroGenerated.Shipping.Builder clearWidth() {
      width = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'height' field.
      * @return The value.
      */
    public java.lang.CharSequence getHeight() {
      return height;
    }


    /**
      * Sets the value of the 'height' field.
      * @param value The value of 'height'.
      * @return This builder.
      */
    public com.cj.prototype.avroGenerated.Shipping.Builder setHeight(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.height = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'height' field has been set.
      * @return True if the 'height' field has been set, false otherwise.
      */
    public boolean hasHeight() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'height' field.
      * @return This builder.
      */
    public com.cj.prototype.avroGenerated.Shipping.Builder clearHeight() {
      height = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Shipping build() {
      try {
        Shipping record = new Shipping();
        if (priceBuilder != null) {
          try {
            record.price = this.priceBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("price"));
            throw e;
          }
        } else {
          record.price = fieldSetFlags()[0] ? this.price : (com.cj.prototype.avroGenerated.AmountWithCurrency) defaultValue(fields()[0]);
        }
        record.service = fieldSetFlags()[1] ? this.service : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.locationGroupName = fieldSetFlags()[2] ? this.locationGroupName : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.region = fieldSetFlags()[3] ? this.region : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.postalCode = fieldSetFlags()[4] ? this.postalCode : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.locationId = fieldSetFlags()[5] ? this.locationId : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.country = fieldSetFlags()[6] ? this.country : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.weight = fieldSetFlags()[7] ? this.weight : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.length = fieldSetFlags()[8] ? this.length : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.width = fieldSetFlags()[9] ? this.width : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.height = fieldSetFlags()[10] ? this.height : (java.lang.CharSequence) defaultValue(fields()[10]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Shipping>
    WRITER$ = (org.apache.avro.io.DatumWriter<Shipping>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Shipping>
    READER$ = (org.apache.avro.io.DatumReader<Shipping>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    this.price.customEncode(out);

    if (this.service == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.service);
    }

    if (this.locationGroupName == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.locationGroupName);
    }

    if (this.region == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.region);
    }

    if (this.postalCode == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.postalCode);
    }

    if (this.locationId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.locationId);
    }

    if (this.country == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.country);
    }

    if (this.weight == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.weight);
    }

    if (this.length == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.length);
    }

    if (this.width == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.width);
    }

    if (this.height == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.height);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (this.price == null) {
        this.price = new com.cj.prototype.avroGenerated.AmountWithCurrency();
      }
      this.price.customDecode(in);

      if (in.readIndex() != 1) {
        in.readNull();
        this.service = null;
      } else {
        this.service = in.readString(this.service instanceof Utf8 ? (Utf8)this.service : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.locationGroupName = null;
      } else {
        this.locationGroupName = in.readString(this.locationGroupName instanceof Utf8 ? (Utf8)this.locationGroupName : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.region = null;
      } else {
        this.region = in.readString(this.region instanceof Utf8 ? (Utf8)this.region : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.postalCode = null;
      } else {
        this.postalCode = in.readString(this.postalCode instanceof Utf8 ? (Utf8)this.postalCode : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.locationId = null;
      } else {
        this.locationId = in.readString(this.locationId instanceof Utf8 ? (Utf8)this.locationId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.country = null;
      } else {
        this.country = in.readString(this.country instanceof Utf8 ? (Utf8)this.country : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.weight = null;
      } else {
        this.weight = in.readString(this.weight instanceof Utf8 ? (Utf8)this.weight : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.length = null;
      } else {
        this.length = in.readString(this.length instanceof Utf8 ? (Utf8)this.length : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.width = null;
      } else {
        this.width = in.readString(this.width instanceof Utf8 ? (Utf8)this.width : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.height = null;
      } else {
        this.height = in.readString(this.height instanceof Utf8 ? (Utf8)this.height : null);
      }

    } else {
      for (int i = 0; i < 11; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (this.price == null) {
            this.price = new com.cj.prototype.avroGenerated.AmountWithCurrency();
          }
          this.price.customDecode(in);
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.service = null;
          } else {
            this.service = in.readString(this.service instanceof Utf8 ? (Utf8)this.service : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.locationGroupName = null;
          } else {
            this.locationGroupName = in.readString(this.locationGroupName instanceof Utf8 ? (Utf8)this.locationGroupName : null);
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.region = null;
          } else {
            this.region = in.readString(this.region instanceof Utf8 ? (Utf8)this.region : null);
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.postalCode = null;
          } else {
            this.postalCode = in.readString(this.postalCode instanceof Utf8 ? (Utf8)this.postalCode : null);
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.locationId = null;
          } else {
            this.locationId = in.readString(this.locationId instanceof Utf8 ? (Utf8)this.locationId : null);
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.country = null;
          } else {
            this.country = in.readString(this.country instanceof Utf8 ? (Utf8)this.country : null);
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.weight = null;
          } else {
            this.weight = in.readString(this.weight instanceof Utf8 ? (Utf8)this.weight : null);
          }
          break;

        case 8:
          if (in.readIndex() != 1) {
            in.readNull();
            this.length = null;
          } else {
            this.length = in.readString(this.length instanceof Utf8 ? (Utf8)this.length : null);
          }
          break;

        case 9:
          if (in.readIndex() != 1) {
            in.readNull();
            this.width = null;
          } else {
            this.width = in.readString(this.width instanceof Utf8 ? (Utf8)this.width : null);
          }
          break;

        case 10:
          if (in.readIndex() != 1) {
            in.readNull();
            this.height = null;
          } else {
            this.height = in.readString(this.height instanceof Utf8 ? (Utf8)this.height : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










